# Generated by Django 5.0.6 on 2024-06-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_bio_remove_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='segundo_nombre',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
