# Generated by Django 5.0.6 on 2024-06-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_date_of_birth_profile_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='numero_celular',
            new_name='celular',
        ),
    ]
