# Generated by Django 5.0.6 on 2024-06-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
