# Generated by Django 5.0.6 on 2024-06-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_carrito_carritoitem_carrito_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
