# Generated by Django 5.0.6 on 2024-06-26 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_carritoitem_carrito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletacompra',
            name='detalles',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='boletacompra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.boletacompra'),
            preserve_default=False,
        ),
    ]
